site_name: Python Module
site_description: Python Training for BSIT Students (Kings College)

nav:
  - Getting Started: index.md
  - Introduction to Python: lectures/1.Introduction.md
  - Data Types: lectures/2.DataTypes.md
  - Control Structures: lectures/3.ControlStructures.md
  - Data Structures: lectures/4.DataStructures.md
  - Functions: lectures/5.Functions.md
  # - File Handling: lectures/6.FileHandling.md
  # - OOP: lectures/7.OOP.md
  # - Errors and Exceptions: lectures/8.ErrorDebugging.md
  # - Advanced Topics: lectures/9.AdvancedConcepts.md
  # - Python Download: index.md

theme:
  name: material
  features:
    - header.autohide
    - announce.dismiss
    - navigation.footer
  code:
    highlighting: true
    light: default
    dark: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  # You can remove 'codehilite' if pymdownx.highlight covers your needs

extra:
  generator: false
      
copyright: Copyright &copy; 2025 - Aayush Raj Regmi
